language: c++

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9.3

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then date -u; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then uname -a; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install mesa-common-dev libgl1-mesa-dev mesa-utils-extra libglapi-mesa ninja-build libqt4-dev qt4-qmake libqt4-opengl-dev; fi

script:
  - cd bin
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cmake -GNinja -DTRAVIS_BUILD:BOOL=ON ../Superbuild; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then cmake -DTRAVIS_BUILD:BOOL=ON ../Superbuild; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; travis_wait 80 ninja; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; make -j4; fi
  - cd SCIRun
  - ./Algorithm_Layer_Test
  - ./Modules_Factory_Tests --gtest_filter=*HardCodedModuleFactoryTests*

notifications:
  slack: sciinstitute:lZnpQQXNd4Io5iGDPQDpJmI1
